import HoloCard from './HoloCard'

function DotDivider() {
  return (
    <div className="relative h-px w-full my-3">
      <div className="absolute inset-0 bg-gradient-to-r from-transparent via-sky-400/40 to-transparent" />
      <div className="absolute left-1/2 -translate-x-1/2 -top-[3px] h-1.5 w-1.5 rounded-full bg-sky-400 shadow-[0_0_12px_2px_rgba(56,189,248,0.55)]" />
    </div>
  )
}

function DataGrid() {
  return (
    <section className="relative z-10 -mt-8 pb-20">
      <div className="container mx-auto px-6 md:px-10">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <HoloCard title="Identitas Utama" footer="Data integrity 99.997% • Last sync: 2m ago">
            <div className="space-y-2">
              <div className="text-xs text-sky-300/70 uppercase tracking-wider">Nama Pengguna</div>
              <div className="text-sky-100/95 font-medium">Maulana Niko Ainul Yaqin</div>
              <DotDivider />
              <div className="text-xs text-sky-300/70 uppercase tracking-wider">Biodata</div>
              <div>Lahir 7 April 2009, Gresik, Jawa Timur</div>
            </div>
          </HoloCard>

          <HoloCard title="Riwayat Pendidikan" footer="Autoclassified by edu-parser">
            <ul className="list-disc list-inside space-y-2 marker:text-sky-400/70">
              <li>Lulusan MI At-Taufiq — tahfidz juz 29–30 (2021–2022)</li>
              <li>Lulusan MTS Ma’arif NU Randegansari</li>
              <li>Alumni Pondok Pesantren Al-Munawaroh total 3 tahun (2024–2025)</li>
            </ul>
          </HoloCard>

          <HoloCard title="Keahlian Inti" footer="Confidence index: high">
            <div className="grid grid-cols-2 gap-3">
              {['Bahasa Inggris','Bahasa Indonesia','Teknologi dasar–menengah','Al-Qur\'an','Pemahaman finansial'].map((skill) => (
                <div key={skill} className="rounded-md border border-sky-400/20 bg-sky-400/5 px-3 py-2 text-sm">
                  <div className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-fuchsia-400 animate-pulse" />
                    <span>{skill}</span>
                  </div>
                </div>
              ))}
            </div>
          </HoloCard>

          <HoloCard title="Aset & Tabungan" footer="Risk profile: growth-oriented">
            <div className="space-y-2">
              <div className="flex items-center justify-between text-sm">
                <span>Investasi Crypto (jangka panjang)</span>
                <span className="text-sky-300/80">• Diversified</span>
              </div>
              <DotDivider />
              <div className="text-xs text-sky-300/70">Status pemantauan otomatis diaktifkan. Fluktuasi ditampilkan dalam grafik halus.</div>
            </div>
          </HoloCard>

          <HoloCard title="Analitik Ringkas" footer="Generated by cognitive-engine v4">
            <div className="grid grid-cols-3 gap-3 text-center">
              {[['Integrity','99.9%'],['Growth','↑ 12%'],['Focus','AI+Edu']].map(([k,v]) => (
                <div key={k} className="rounded-md border border-white/5 bg-slate-800/50 p-3">
                  <div className="text-[10px] uppercase tracking-wider text-sky-300/70">{k}</div>
                  <div className="mt-1 text-sky-100 text-lg font-semibold">{v}</div>
                </div>
              ))}
            </div>
          </HoloCard>

          <HoloCard title="Grafik Aktivitas" footer="Smoothed signal">
            <div className="relative h-28">
              <svg viewBox="0 0 300 100" className="absolute inset-0">
                <defs>
                  <linearGradient id="g" x1="0" x2="1">
                    <stop offset="0%" stopColor="#38bdf8" stopOpacity="0.7"/>
                    <stop offset="100%" stopColor="#a78bfa" stopOpacity="0.7"/>
                  </linearGradient>
                </defs>
                <path d="M0 60 C 30 20, 60 80, 90 50 S 150 40, 180 60 240 70, 300 50" fill="none" stroke="url(#g)" strokeWidth="2" className="drop-shadow-[0_0_8px_rgba(56,189,248,0.4)]"/>
                <g className="opacity-30">
                  {Array.from({length:12}).map((_,i)=> (
                    <line key={i} x1={(i+1)*25} y1="0" x2={(i+1)*25} y2="100" stroke="rgba(148,163,184,0.25)" strokeWidth="0.5" />
                  ))}
                </g>
              </svg>
            </div>
          </HoloCard>
        </div>
      </div>
    </section>
  )
}

export default DataGrid
